-- MySQL Script generated by MySQL Workbench
-- 01/22/20 11:28:23
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema wwf_shrimp_database_v2
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `wwf_shrimp_database_v2` ;

-- -----------------------------------------------------
-- Schema wwf_shrimp_database_v2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `wwf_shrimp_database_v2` DEFAULT CHARACTER SET utf8mb4 ;
USE `wwf_shrimp_database_v2` ;

-- -----------------------------------------------------
-- Table `wwf_shrimp_database_v2`.`app_resources`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wwf_shrimp_database_v2`.`app_resources` ;

CREATE TABLE IF NOT EXISTS `wwf_shrimp_database_v2`.`app_resources` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `resource_key` VARCHAR(255) NULL DEFAULT NULL,
  `value` VARCHAR(4000) NULL DEFAULT NULL,
  `locale` VARCHAR(10) NULL DEFAULT NULL,
  `type` VARCHAR(100) NULL DEFAULT 'document',
  `sub_type` VARCHAR(100) NULL DEFAULT 'type metadata',
  `platform` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 541
DEFAULT CHARACTER SET = utf8mb4
COMMENT = 'Resource Table for internationalized resources.\nNOTE: locale is the locale/langauge ISO code.\nIn general English (en) should always be present and should be defaulted to if other locale is not found';


-- -----------------------------------------------------
-- Table `wwf_shrimp_database_v2`.`audit_data`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wwf_shrimp_database_v2`.`audit_data` ;

CREATE TABLE IF NOT EXISTS `wwf_shrimp_database_v2`.`audit_data` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `actor_name` VARCHAR(200) NOT NULL,
  `actor_type` VARCHAR(64) NULL DEFAULT NULL,
  `action` VARCHAR(200) NOT NULL,
  `item_type` VARCHAR(200) NOT NULL,
  `item_id` VARCHAR(200) NOT NULL,
  `field` VARCHAR(200) NULL DEFAULT NULL,
  `previous_value` VARCHAR(200) NULL DEFAULT NULL,
  `new_value` VARCHAR(200) NULL DEFAULT NULL,
  `timestamp` VARCHAR(64) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1837
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `wwf_shrimp_database_v2`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wwf_shrimp_database_v2`.`user` ;

CREATE TABLE IF NOT EXISTS `wwf_shrimp_database_v2`.`user` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NOT NULL,
  `password` VARCHAR(64) NOT NULL,
  `delete_flag` TINYINT(1) NULL DEFAULT '0',
  `profile_image` LONGBLOB NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `name`))
ENGINE = InnoDB
AUTO_INCREMENT = 151
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `wwf_shrimp_database_v2`.`document`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wwf_shrimp_database_v2`.`document` ;

CREATE TABLE IF NOT EXISTS `wwf_shrimp_database_v2`.`document` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `description` VARCHAR(200) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `associated_template_id` BIGINT(20) NULL DEFAULT NULL,
  `document_type_id` BIGINT(20) NOT NULL,
  `delete_flag` TINYINT(1) NULL DEFAULT '0',
  `userid` BIGINT(20) NULL DEFAULT NULL,
  `username` VARCHAR(200) CHARACTER SET 'utf8' NOT NULL,
  `document_type` VARCHAR(200) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `creation_timestamp` VARCHAR(64) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `document_image_blob` MEDIUMBLOB NULL DEFAULT NULL,
  `document_image_uri` VARCHAR(256) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `type_hex_color` VARCHAR(200) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `sync_id` VARCHAR(36) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `organization_id` BIGINT(20) NOT NULL DEFAULT '1',
  `group_id` BIGINT(20) NOT NULL DEFAULT '1',
  `doc_status` VARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT 'DRAFT',
  `gps_location` VARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `document_type_id`, `username`, `group_id`, `organization_id`),
  CONSTRAINT `fk_document_user1`
    FOREIGN KEY (`userid` , `username`)
    REFERENCES `wwf_shrimp_database_v2`.`user` (`id` , `name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1142
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_document_user1_idx` ON `wwf_shrimp_database_v2`.`document` (`userid` ASC, `username` ASC);


-- -----------------------------------------------------
-- Table `wwf_shrimp_database_v2`.`document_attachment_data`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wwf_shrimp_database_v2`.`document_attachment_data` ;

CREATE TABLE IF NOT EXISTS `wwf_shrimp_database_v2`.`document_attachment_data` (
  `parent_doc_id` BIGINT(20) NOT NULL,
  `attached_doc_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`parent_doc_id`, `attached_doc_id`),
  CONSTRAINT `fk_attached_document_child`
    FOREIGN KEY (`attached_doc_id`)
    REFERENCES `wwf_shrimp_database_v2`.`document` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_attached_document_parent`
    FOREIGN KEY (`parent_doc_id`)
    REFERENCES `wwf_shrimp_database_v2`.`document` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_attached_document_child_idx` ON `wwf_shrimp_database_v2`.`document_attachment_data` (`attached_doc_id` ASC);


-- -----------------------------------------------------
-- Table `wwf_shrimp_database_v2`.`entity_data`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wwf_shrimp_database_v2`.`entity_data` ;

CREATE TABLE IF NOT EXISTS `wwf_shrimp_database_v2`.`entity_data` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `value` BLOB NULL DEFAULT NULL,
  `data_type` VARCHAR(264) NULL DEFAULT NULL,
  `is_required` TINYINT(1) NULL DEFAULT '0',
  `delete_flag` TINYINT(1) NULL DEFAULT '0',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `wwf_shrimp_database_v2`.`document_entity_data`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wwf_shrimp_database_v2`.`document_entity_data` ;

CREATE TABLE IF NOT EXISTS `wwf_shrimp_database_v2`.`document_entity_data` (
  `document_id` BIGINT(20) NOT NULL,
  `entity_data_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`document_id`, `entity_data_id`),
  CONSTRAINT `fk_document_entity_data_document1`
    FOREIGN KEY (`document_id`)
    REFERENCES `wwf_shrimp_database_v2`.`document` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_document_entity_data_entity_data1`
    FOREIGN KEY (`entity_data_id`)
    REFERENCES `wwf_shrimp_database_v2`.`entity_data` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_document_entity_data_entity_data1_idx` ON `wwf_shrimp_database_v2`.`document_entity_data` (`entity_data_id` ASC);

CREATE INDEX `fk_document_entity_data_document1_idx` ON `wwf_shrimp_database_v2`.`document_entity_data` (`document_id` ASC);


-- -----------------------------------------------------
-- Table `wwf_shrimp_database_v2`.`document_import`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wwf_shrimp_database_v2`.`document_import` ;

CREATE TABLE IF NOT EXISTS `wwf_shrimp_database_v2`.`document_import` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `doc_import_id` BIGINT(20) NOT NULL,
  `file_data` LONGBLOB NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 110
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `wwf_shrimp_database_v2`.`document_link_data`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wwf_shrimp_database_v2`.`document_link_data` ;

CREATE TABLE IF NOT EXISTS `wwf_shrimp_database_v2`.`document_link_data` (
  `parent_doc_id` BIGINT(20) NOT NULL,
  `linked_doc_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`parent_doc_id`, `linked_doc_id`),
  CONSTRAINT `fk_document_child`
    FOREIGN KEY (`linked_doc_id`)
    REFERENCES `wwf_shrimp_database_v2`.`document` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_document_parent`
    FOREIGN KEY (`parent_doc_id`)
    REFERENCES `wwf_shrimp_database_v2`.`document` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_document_child_idx` ON `wwf_shrimp_database_v2`.`document_link_data` (`linked_doc_id` ASC);


-- -----------------------------------------------------
-- Table `wwf_shrimp_database_v2`.`document_location_data`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wwf_shrimp_database_v2`.`document_location_data` ;

CREATE TABLE IF NOT EXISTS `wwf_shrimp_database_v2`.`document_location_data` (
  `document_sync_id` VARCHAR(36) NOT NULL,
  `gps_location` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`document_sync_id`, `gps_location`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `wwf_shrimp_database_v2`.`document_notes_data`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wwf_shrimp_database_v2`.`document_notes_data` ;

CREATE TABLE IF NOT EXISTS `wwf_shrimp_database_v2`.`document_notes_data` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `parent_doc_id` BIGINT(20) NULL DEFAULT NULL,
  `timestamp` VARCHAR(64) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `ordinal` INT(11) NOT NULL DEFAULT '0',
  `note_data` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `note_data_header` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `creator_user` VARCHAR(64) CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`id`, `ordinal`))
ENGINE = InnoDB
AUTO_INCREMENT = 41
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `wwf_shrimp_database_v2`.`document_org_group_rel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wwf_shrimp_database_v2`.`document_org_group_rel` ;

CREATE TABLE IF NOT EXISTS `wwf_shrimp_database_v2`.`document_org_group_rel` (
  `id` BIGINT(20) NOT NULL,
  `doc_id` BIGINT(20) NOT NULL,
  `organization_id` BIGINT(20) NOT NULL,
  `group_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_document_idx_idx` ON `wwf_shrimp_database_v2`.`document_org_group_rel` (`doc_id` ASC);

CREATE INDEX `fk_group_idx_idx` ON `wwf_shrimp_database_v2`.`document_org_group_rel` (`group_id` ASC);


-- -----------------------------------------------------
-- Table `wwf_shrimp_database_v2`.`document_page`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wwf_shrimp_database_v2`.`document_page` ;

CREATE TABLE IF NOT EXISTS `wwf_shrimp_database_v2`.`document_page` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `page_number` INT(11) NULL DEFAULT NULL,
  `page_data` MEDIUMBLOB NULL DEFAULT NULL,
  `document_id` BIGINT(20) NOT NULL,
  `delete_flag` TINYINT(1) NULL DEFAULT '0',
  `page_data_uri` VARCHAR(256) NULL DEFAULT NULL,
  `page_data_type` VARCHAR(200) NULL DEFAULT NULL,
  `page_data_thumbnail` MEDIUMBLOB NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `document_id`),
  CONSTRAINT `fk_DocumentPage_Document1`
    FOREIGN KEY (`document_id`)
    REFERENCES `wwf_shrimp_database_v2`.`document` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1760
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_DocumentPage_Document1_idx` ON `wwf_shrimp_database_v2`.`document_page` (`document_id` ASC);


-- -----------------------------------------------------
-- Table `wwf_shrimp_database_v2`.`document_page_entity_data`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wwf_shrimp_database_v2`.`document_page_entity_data` ;

CREATE TABLE IF NOT EXISTS `wwf_shrimp_database_v2`.`document_page_entity_data` (
  `document_page_id` BIGINT(20) NOT NULL,
  `entity_data_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`document_page_id`, `entity_data_id`),
  CONSTRAINT `fk_document_page_entity_data_document_page1`
    FOREIGN KEY (`document_page_id`)
    REFERENCES `wwf_shrimp_database_v2`.`document_page` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_document_page_entity_data_entity_data1`
    FOREIGN KEY (`entity_data_id`)
    REFERENCES `wwf_shrimp_database_v2`.`entity_data` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_document_page_entity_data_entity_data1_idx` ON `wwf_shrimp_database_v2`.`document_page_entity_data` (`entity_data_id` ASC);

CREATE INDEX `fk_document_page_entity_data_document_page1_idx` ON `wwf_shrimp_database_v2`.`document_page_entity_data` (`document_page_id` ASC);


-- -----------------------------------------------------
-- Table `wwf_shrimp_database_v2`.`document_recipient_data`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wwf_shrimp_database_v2`.`document_recipient_data` ;

CREATE TABLE IF NOT EXISTS `wwf_shrimp_database_v2`.`document_recipient_data` (
  `parent_doc_id` BIGINT(20) NOT NULL,
  `to_user_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`parent_doc_id`, `to_user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `wwf_shrimp_database_v2`.`tag_data`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wwf_shrimp_database_v2`.`tag_data` ;

CREATE TABLE IF NOT EXISTS `wwf_shrimp_database_v2`.`tag_data` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `tag_text` VARCHAR(200) NOT NULL,
  `delete_flag` TINYINT(1) NULL DEFAULT '0',
  `custom_tag_prefix` VARCHAR(45) NULL DEFAULT NULL,
  `organization_id` BIGINT(20) NULL DEFAULT NULL,
  `custom` TINYINT(1) NULL DEFAULT '0',
  `owner` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 197
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `wwf_shrimp_database_v2`.`document_tag_data`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wwf_shrimp_database_v2`.`document_tag_data` ;

CREATE TABLE IF NOT EXISTS `wwf_shrimp_database_v2`.`document_tag_data` (
  `document_id` BIGINT(20) NOT NULL,
  `tag_data_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`document_id`, `tag_data_id`),
  CONSTRAINT `fk_document_tag_data_document1`
    FOREIGN KEY (`document_id`)
    REFERENCES `wwf_shrimp_database_v2`.`document` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_document_tag_data_tag_data1`
    FOREIGN KEY (`tag_data_id`)
    REFERENCES `wwf_shrimp_database_v2`.`tag_data` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_document_tag_data_tag_data1_idx` ON `wwf_shrimp_database_v2`.`document_tag_data` (`tag_data_id` ASC);

CREATE INDEX `fk_document_tag_data_document1_idx` ON `wwf_shrimp_database_v2`.`document_tag_data` (`document_id` ASC);


-- -----------------------------------------------------
-- Table `wwf_shrimp_database_v2`.`document_template`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wwf_shrimp_database_v2`.`document_template` ;

CREATE TABLE IF NOT EXISTS `wwf_shrimp_database_v2`.`document_template` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NULL DEFAULT NULL,
  `description` VARCHAR(1000) NULL DEFAULT NULL,
  `min_pages` INT(11) NULL DEFAULT NULL,
  `max_pages` INT(11) NULL DEFAULT NULL,
  `version` VARCHAR(7) NULL DEFAULT NULL,
  `document_type_id` BIGINT(20) NOT NULL,
  `delete_flag` TINYINT(1) NULL DEFAULT '0',
  PRIMARY KEY (`id`, `document_type_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `wwf_shrimp_database_v2`.`document_template_entity_data`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wwf_shrimp_database_v2`.`document_template_entity_data` ;

CREATE TABLE IF NOT EXISTS `wwf_shrimp_database_v2`.`document_template_entity_data` (
  `document_template_id` BIGINT(20) NOT NULL,
  `entity_data_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`document_template_id`, `entity_data_id`),
  CONSTRAINT `fk_document_template_entity_data_document_template1`
    FOREIGN KEY (`document_template_id`)
    REFERENCES `wwf_shrimp_database_v2`.`document_template` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_document_template_entity_data_entity_data1`
    FOREIGN KEY (`entity_data_id`)
    REFERENCES `wwf_shrimp_database_v2`.`entity_data` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_document_template_entity_data_entity_data1_idx` ON `wwf_shrimp_database_v2`.`document_template_entity_data` (`entity_data_id` ASC);

CREATE INDEX `fk_document_template_entity_data_document_template1_idx` ON `wwf_shrimp_database_v2`.`document_template_entity_data` (`document_template_id` ASC);


-- -----------------------------------------------------
-- Table `wwf_shrimp_database_v2`.`document_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wwf_shrimp_database_v2`.`document_type` ;

CREATE TABLE IF NOT EXISTS `wwf_shrimp_database_v2`.`document_type` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NULL DEFAULT NULL,
  `value` VARCHAR(200) NULL DEFAULT NULL,
  `color_hex_code` VARCHAR(10) NULL DEFAULT NULL,
  `document_designation` VARCHAR(45) NULL DEFAULT NULL,
  `delete_flag` TINYINT(1) NULL DEFAULT '0',
  `is_resource` TINYINT(1) NULL DEFAULT '1',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 87
DEFAULT CHARACTER SET = utf8
COMMENT = 'name - is the key to the resource name of the data\nvalue - will be ommited in future versions and will be looked up based on the key (i.e. name)';


-- -----------------------------------------------------
-- Table `wwf_shrimp_database_v2`.`group_allowed_doctype_rel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wwf_shrimp_database_v2`.`group_allowed_doctype_rel` ;

CREATE TABLE IF NOT EXISTS `wwf_shrimp_database_v2`.`group_allowed_doctype_rel` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `parent_group_type_id` BIGINT(20) NULL DEFAULT NULL,
  `doc_type_ids` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 400
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `wwf_shrimp_database_v2`.`group_data`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wwf_shrimp_database_v2`.`group_data` ;

CREATE TABLE IF NOT EXISTS `wwf_shrimp_database_v2`.`group_data` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NULL DEFAULT NULL,
  `description` VARCHAR(2000) NULL DEFAULT NULL,
  `delete_flag` TINYINT(1) NULL DEFAULT '0',
  `group_data_type_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`, `group_data_type_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 120
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `wwf_shrimp_database_v2`.`group_data_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wwf_shrimp_database_v2`.`group_data_type` ;

CREATE TABLE IF NOT EXISTS `wwf_shrimp_database_v2`.`group_data_type` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(25) NULL DEFAULT NULL,
  `value` VARCHAR(200) NULL DEFAULT NULL,
  `color_hex_code` VARCHAR(10) NULL DEFAULT NULL,
  `order_index` INT(11) NOT NULL DEFAULT '0',
  `is_resource` TINYINT(1) NULL DEFAULT '1',
  `org_id` BIGINT(20) NOT NULL DEFAULT '0',
  `value_id` BIGINT(20) NULL DEFAULT '0',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 483
DEFAULT CHARACTER SET = utf8
COMMENT = 'name - is the key to the resource name of the data\nvalue - will be ommited in future versions and will be looked up based on the key (i.e. name)\nvalue_id - will be used to fetch internationalized values for the actual name.';


-- -----------------------------------------------------
-- Table `wwf_shrimp_database_v2`.`group_group_rel_tree`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wwf_shrimp_database_v2`.`group_group_rel_tree` ;

CREATE TABLE IF NOT EXISTS `wwf_shrimp_database_v2`.`group_group_rel_tree` (
  `id` BIGINT(20) NOT NULL,
  `parent_group_id` BIGINT(20) NULL DEFAULT NULL,
  `child_group_id` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_group_child`
    FOREIGN KEY (`child_group_id`)
    REFERENCES `wwf_shrimp_database_v2`.`group_data` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_group_child_idx` ON `wwf_shrimp_database_v2`.`group_group_rel_tree` (`child_group_id` ASC);


-- -----------------------------------------------------
-- Table `wwf_shrimp_database_v2`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wwf_shrimp_database_v2`.`role` ;

CREATE TABLE IF NOT EXISTS `wwf_shrimp_database_v2`.`role` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(25) NULL DEFAULT NULL,
  `value` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `wwf_shrimp_database_v2`.`group_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wwf_shrimp_database_v2`.`group_role` ;

CREATE TABLE IF NOT EXISTS `wwf_shrimp_database_v2`.`group_role` (
  `group_id` BIGINT(20) NOT NULL,
  `role_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`group_id`, `role_id`),
  CONSTRAINT `fk_group_role_group1`
    FOREIGN KEY (`group_id`)
    REFERENCES `wwf_shrimp_database_v2`.`group_data` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_group_role_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `wwf_shrimp_database_v2`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_group_role_role1_idx` ON `wwf_shrimp_database_v2`.`group_role` (`role_id` ASC);

CREATE INDEX `fk_group_role_group1_idx` ON `wwf_shrimp_database_v2`.`group_role` (`group_id` ASC);


-- -----------------------------------------------------
-- Table `wwf_shrimp_database_v2`.`metadata_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wwf_shrimp_database_v2`.`metadata_type` ;

CREATE TABLE IF NOT EXISTS `wwf_shrimp_database_v2`.`metadata_type` (
  `id` BIGINT(20) NOT NULL,
  `name` VARCHAR(25) NULL DEFAULT NULL,
  `value` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `wwf_shrimp_database_v2`.`metadata`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wwf_shrimp_database_v2`.`metadata` ;

CREATE TABLE IF NOT EXISTS `wwf_shrimp_database_v2`.`metadata` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NULL DEFAULT NULL,
  `text_value` VARCHAR(200) NULL DEFAULT NULL,
  `long_text_value` LONGTEXT NULL DEFAULT NULL,
  `object_value` LONGBLOB NULL DEFAULT NULL,
  `metadata_type_id` BIGINT(20) NOT NULL,
  `document_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`, `metadata_type_id`, `document_id`),
  CONSTRAINT `fk_Metadata_Document1`
    FOREIGN KEY (`document_id`)
    REFERENCES `wwf_shrimp_database_v2`.`document` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Metadata_MetadataType1`
    FOREIGN KEY (`metadata_type_id`)
    REFERENCES `wwf_shrimp_database_v2`.`metadata_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_Metadata_MetadataType1_idx` ON `wwf_shrimp_database_v2`.`metadata` (`metadata_type_id` ASC);

CREATE INDEX `fk_Metadata_Document1_idx` ON `wwf_shrimp_database_v2`.`metadata` (`document_id` ASC);


-- -----------------------------------------------------
-- Table `wwf_shrimp_database_v2`.`notification`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wwf_shrimp_database_v2`.`notification` ;

CREATE TABLE IF NOT EXISTS `wwf_shrimp_database_v2`.`notification` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `userid` BIGINT(20) NULL DEFAULT NULL,
  `notification_type` VARCHAR(200) NULL DEFAULT NULL,
  `creation_timestamp` VARCHAR(64) NULL DEFAULT NULL,
  `notification_timestamp` VARCHAR(64) NULL DEFAULT NULL,
  `auditId` BIGINT(20) NULL DEFAULT NULL,
  `text` VARCHAR(256) NULL DEFAULT NULL,
  `description` VARCHAR(1000) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 406
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `wwf_shrimp_database_v2`.`organization`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wwf_shrimp_database_v2`.`organization` ;

CREATE TABLE IF NOT EXISTS `wwf_shrimp_database_v2`.`organization` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NULL DEFAULT NULL,
  `description` VARCHAR(1024) NULL DEFAULT NULL,
  `delete_flag` TINYINT(1) NULL DEFAULT '0',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `wwf_shrimp_database_v2`.`organization_group_rel_tree`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wwf_shrimp_database_v2`.`organization_group_rel_tree` ;

CREATE TABLE IF NOT EXISTS `wwf_shrimp_database_v2`.`organization_group_rel_tree` (
  `parent_org_id` BIGINT(20) NOT NULL,
  `group_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`parent_org_id`, `group_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `wwf_shrimp_database_v2`.`resource_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wwf_shrimp_database_v2`.`resource_type` ;

CREATE TABLE IF NOT EXISTS `wwf_shrimp_database_v2`.`resource_type` (
  `id` BIGINT(20) NOT NULL,
  `name` VARCHAR(25) NULL DEFAULT NULL,
  `value` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `wwf_shrimp_database_v2`.`resource`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wwf_shrimp_database_v2`.`resource` ;

CREATE TABLE IF NOT EXISTS `wwf_shrimp_database_v2`.`resource` (
  `Id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `resource_object_id` BIGINT(20) NOT NULL,
  `name` VARCHAR(200) NULL DEFAULT NULL,
  `resource_type_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`Id`, `resource_object_id`, `resource_type_id`),
  CONSTRAINT `fk_resource_resource_type1`
    FOREIGN KEY (`resource_type_id`)
    REFERENCES `wwf_shrimp_database_v2`.`resource_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_resource_resource_type1_idx` ON `wwf_shrimp_database_v2`.`resource` (`resource_type_id` ASC);


-- -----------------------------------------------------
-- Table `wwf_shrimp_database_v2`.`permission`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wwf_shrimp_database_v2`.`permission` ;

CREATE TABLE IF NOT EXISTS `wwf_shrimp_database_v2`.`permission` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `permission_type` VARCHAR(10) NOT NULL,
  `permission_scope_type` VARCHAR(15) NULL DEFAULT NULL,
  `expiry_date` DATETIME NULL DEFAULT NULL,
  `resource_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`, `permission_type`, `resource_id`),
  CONSTRAINT `fk_Permission_Resource1`
    FOREIGN KEY (`resource_id`)
    REFERENCES `wwf_shrimp_database_v2`.`resource` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_Permission_Resource1_idx` ON `wwf_shrimp_database_v2`.`permission` (`resource_id` ASC);


-- -----------------------------------------------------
-- Table `wwf_shrimp_database_v2`.`role_permission`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wwf_shrimp_database_v2`.`role_permission` ;

CREATE TABLE IF NOT EXISTS `wwf_shrimp_database_v2`.`role_permission` (
  `role_id` BIGINT(20) NOT NULL,
  `permission_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`role_id`, `permission_id`),
  CONSTRAINT `fk_role_permission_permission1`
    FOREIGN KEY (`permission_id`)
    REFERENCES `wwf_shrimp_database_v2`.`permission` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_role_permission_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `wwf_shrimp_database_v2`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_role_permission_permission1_idx` ON `wwf_shrimp_database_v2`.`role_permission` (`permission_id` ASC);

CREATE INDEX `fk_role_permission_role1_idx` ON `wwf_shrimp_database_v2`.`role_permission` (`role_id` ASC);


-- -----------------------------------------------------
-- Table `wwf_shrimp_database_v2`.`role_resource`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wwf_shrimp_database_v2`.`role_resource` ;

CREATE TABLE IF NOT EXISTS `wwf_shrimp_database_v2`.`role_resource` (
  `role_id` BIGINT(20) NOT NULL,
  `resource_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`role_id`, `resource_id`),
  CONSTRAINT `fk_role_resource_resource1`
    FOREIGN KEY (`resource_id`)
    REFERENCES `wwf_shrimp_database_v2`.`resource` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_role_resource_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `wwf_shrimp_database_v2`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_role_resource_resource1_idx` ON `wwf_shrimp_database_v2`.`role_resource` (`resource_id` ASC);

CREATE INDEX `fk_role_resource_role1_idx` ON `wwf_shrimp_database_v2`.`role_resource` (`role_id` ASC);


-- -----------------------------------------------------
-- Table `wwf_shrimp_database_v2`.`security_token`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wwf_shrimp_database_v2`.`security_token` ;

CREATE TABLE IF NOT EXISTS `wwf_shrimp_database_v2`.`security_token` (
  `user_id` BIGINT(20) NOT NULL,
  `token_value` VARCHAR(256) NOT NULL,
  `expiration_date` DATETIME NOT NULL,
  `invalidated` TINYINT(1) NULL DEFAULT '0',
  PRIMARY KEY (`user_id`, `token_value`),
  CONSTRAINT `fk_security_token_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `wwf_shrimp_database_v2`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_security_token_user1_idx` ON `wwf_shrimp_database_v2`.`security_token` (`user_id` ASC);


-- -----------------------------------------------------
-- Table `wwf_shrimp_database_v2`.`supported_languages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wwf_shrimp_database_v2`.`supported_languages` ;

CREATE TABLE IF NOT EXISTS `wwf_shrimp_database_v2`.`supported_languages` (
  `id` BIGINT(20) NOT NULL,
  `name` VARCHAR(5) NOT NULL,
  `value` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = 'name - the iso code for the language\nvalue - the full name of the supported language';


-- -----------------------------------------------------
-- Table `wwf_shrimp_database_v2`.`supported_languages_org_rel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wwf_shrimp_database_v2`.`supported_languages_org_rel` ;

CREATE TABLE IF NOT EXISTS `wwf_shrimp_database_v2`.`supported_languages_org_rel` (
  `org_id` INT(20) NOT NULL,
  `language_id` INT(20) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `wwf_shrimp_database_v2`.`tag_prefix_lu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wwf_shrimp_database_v2`.`tag_prefix_lu` ;

CREATE TABLE IF NOT EXISTS `wwf_shrimp_database_v2`.`tag_prefix_lu` (
  `id` BIGINT(20) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `value` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `wwf_shrimp_database_v2`.`trace_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wwf_shrimp_database_v2`.`trace_type` ;

CREATE TABLE IF NOT EXISTS `wwf_shrimp_database_v2`.`trace_type` (
  `id` BIGINT(20) NOT NULL,
  `name` VARCHAR(25) NULL DEFAULT NULL,
  `value` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `wwf_shrimp_database_v2`.`trace_data`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wwf_shrimp_database_v2`.`trace_data` ;

CREATE TABLE IF NOT EXISTS `wwf_shrimp_database_v2`.`trace_data` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `global_transaction_id` BIGINT(20) NULL DEFAULT NULL,
  `trace_type_id` BIGINT(20) NOT NULL,
  `resource_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`, `trace_type_id`, `resource_id`),
  CONSTRAINT `fk_trace_Data_resource1`
    FOREIGN KEY (`resource_id`)
    REFERENCES `wwf_shrimp_database_v2`.`resource` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_trace_Data_trace_type1`
    FOREIGN KEY (`trace_type_id`)
    REFERENCES `wwf_shrimp_database_v2`.`trace_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_trace_Data_trace_type1_idx` ON `wwf_shrimp_database_v2`.`trace_data` (`trace_type_id` ASC);

CREATE INDEX `fk_trace_Data_resource1_idx` ON `wwf_shrimp_database_v2`.`trace_data` (`resource_id` ASC);


-- -----------------------------------------------------
-- Table `wwf_shrimp_database_v2`.`user_contact`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wwf_shrimp_database_v2`.`user_contact` ;

CREATE TABLE IF NOT EXISTS `wwf_shrimp_database_v2`.`user_contact` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `email_address` VARCHAR(200) NULL DEFAULT NULL,
  `cell_number` VARCHAR(15) NULL DEFAULT NULL,
  `user_id` BIGINT(20) NOT NULL,
  `first_name` VARCHAR(45) NULL DEFAULT NULL,
  `last_name` VARCHAR(100) NULL DEFAULT NULL,
  `nick_name` VARCHAR(45) NULL DEFAULT NULL,
  `line_id` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `user_id`),
  CONSTRAINT `fk_user_contact_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `wwf_shrimp_database_v2`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 151
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_user_contact_user1_idx` ON `wwf_shrimp_database_v2`.`user_contact` (`user_id` ASC);


-- -----------------------------------------------------
-- Table `wwf_shrimp_database_v2`.`user_group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wwf_shrimp_database_v2`.`user_group` ;

CREATE TABLE IF NOT EXISTS `wwf_shrimp_database_v2`.`user_group` (
  `user_id` BIGINT(20) NOT NULL,
  `group_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`user_id`, `group_id`),
  CONSTRAINT `fk_user_group_group1`
    FOREIGN KEY (`group_id`)
    REFERENCES `wwf_shrimp_database_v2`.`group_data` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_group_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `wwf_shrimp_database_v2`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_user_group_group1_idx` ON `wwf_shrimp_database_v2`.`user_group` (`group_id` ASC);

CREATE INDEX `fk_user_group_user1_idx` ON `wwf_shrimp_database_v2`.`user_group` (`user_id` ASC);


-- -----------------------------------------------------
-- Table `wwf_shrimp_database_v2`.`user_organization`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wwf_shrimp_database_v2`.`user_organization` ;

CREATE TABLE IF NOT EXISTS `wwf_shrimp_database_v2`.`user_organization` (
  `user_id` BIGINT(20) NOT NULL,
  `organization_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`user_id`, `organization_id`),
  CONSTRAINT `fk_user_organization_organization1`
    FOREIGN KEY (`organization_id`)
    REFERENCES `wwf_shrimp_database_v2`.`organization` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_organization_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `wwf_shrimp_database_v2`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_user_organization_organization1_idx` ON `wwf_shrimp_database_v2`.`user_organization` (`organization_id` ASC);

CREATE INDEX `fk_user_organization_user1_idx` ON `wwf_shrimp_database_v2`.`user_organization` (`user_id` ASC);


-- -----------------------------------------------------
-- Table `wwf_shrimp_database_v2`.`user_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wwf_shrimp_database_v2`.`user_role` ;

CREATE TABLE IF NOT EXISTS `wwf_shrimp_database_v2`.`user_role` (
  `user_id` BIGINT(20) NOT NULL,
  `role_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`user_id`, `role_id`),
  CONSTRAINT `fk_user_role_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `wwf_shrimp_database_v2`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_role_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `wwf_shrimp_database_v2`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_user_role_role1_idx` ON `wwf_shrimp_database_v2`.`user_role` (`role_id` ASC);

CREATE INDEX `fk_user_role_user1_idx` ON `wwf_shrimp_database_v2`.`user_role` (`user_id` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
